config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # get 'tasks' => 'tasks#index'
  
  root 'tasks#index'
  resources :tasks
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    
    def index
        @tasks = Task.all
        @task = Task.new
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)
        if @task.save
            redirect_to tasks_url
        else
            render :new
        end
    end
    
    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to tasks_url
    end


    private
    def task_params
        params.require(:task).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asgn021RailsTaskList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
    
    <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/tasks/index.html.erb
<%= javascript_pack_tag "task" %>
<h1>Task List</h1>

<%= link_to "Add a Task", new_task_path %>

<%= render partial: "form" %>

<ul>
    <% @tasks.each do |task| %>
        <li>
            <%= link_to "Delete", task_path(task), method: :delete %>    
            <%= task.name %>
        </li>
    <%end%>
</ul>

app/views/tasks/new.html.erb
<h1> Add a Task </h1>

<p>
    <%= link_to "Back to Tasks", tasks_path %>
</p>

<%= render partial: "form" %>